# Generated by Django 4.2.7 on 2023-11-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_scraperstatus_last_message_visited_and_more'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingplan',
            name='target_group',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('app_label', 'scraper'), ('is_target', True), ('model', 'telegramgroup')), on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='scraper.telegramgroup'),
            preserve_default=False,
        ),
    ]
