# Generated by Django 4.2.7 on 2023-11-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_telegramuser_is_bot'),
        ('marketing', '0002_marketingplan_target_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingplan',
            name='target_group',
            field=models.ForeignKey(limit_choices_to={'is_target': True}, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='scraper.telegramgroup'),
        ),
    ]
