# Generated by Django 4.2.7 on 2023-11-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_telegramuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='is_super_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='participants_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
