# Generated by Django 4.2.7 on 2023-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_telegramgroup_is_super_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
