# Generated by Django 4.2.7 on 2023-11-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_telegramgroup_participants_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
