# Generated by Django 4.2.7 on 2023-11-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('scraper', '0007_telegramgroup_deep_crwal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_group_visited', models.BigIntegerField(blank=True, null=True)),
                ('last_user_visited', models.BigIntegerField(blank=True, null=True)),
                ('job', models.CharField(choices=[('sc', 'Scrape Conversations'), ('sug', 'Scrape Users in Groups'), ('sugm', 'Scrape Users in SuperGroups With Message'), ('iuc', 'Invite Users To Channel'), ('iug', 'Invite User To Group'), ('smu', 'Send Message To User')], max_length=10)),
                ('interval', models.IntegerField(default=144)),
                ('status', models.CharField(choices=[('r', 'Running'), ('p', 'Puaused'), ('c', 'Completed')], max_length=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('marketing_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.marketingplan')),
            ],
        ),
    ]
