# Generated by Django 4.2.7 on 2023-11-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_scraperstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperstatus',
            name='last_message_visited',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='is_target',
            field=models.BooleanField(default=False),
        ),
    ]
