# Generated by Django 4.2.7 on 2023-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_scraperstatus_last_message_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='session',
            field=models.TextField(blank=True, null=True),
        ),
    ]
