# Generated by Django 4.2.7 on 2023-11-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_telegramuser_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
